### ISSUE TITLE
I was a good person and changed the title. Unlike normal.

### ISSUE THREAD

**Issue by henryiii** [henryiii/packaging-problems#1]
### OS version

macOS Big Sur

### Python version

Python 3.12

### Pip version

pip 23.9

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I can't find distutils! Where did it go!

### Error message

```pytb
>>> import distutils3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named distutils
```

**Comment by Leoporno** [comment]
[](url)>>> import distutils3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named distutils

**Comment by henryiii** [comment]
This was just a test of the template we added to the main repo (pypa/packaging-problems). Commit there if there's a problem, but FYI distutils was removed in Python 3.12.
